### ISSUE TITLE
Failing to load materials

### ISSUE THREAD

**Issue by confuseth** [Gmod4phun/phunbase_ins2#4]
Weapons are all missing textures on entering the game, after going through all the ironsights all the weapons turn black (also black in the spawnmenu), also no sounds on almost every gun, only the bullet impact ones play.

![2019-02-06_22-12-16](https://user-images.githubusercontent.com/25161663/52374072-99f77500-2a5c-11e9-898b-40f5f7a77a1c.png)
![hl2_2019-02-06_22-12-41](https://user-images.githubusercontent.com/25161663/52374080-9d8afc00-2a5c-11e9-9ccc-08b9f372969c.png)

I don't have insurgency installed so I presume it's that

**Comment by Gmod4phun** [comment]
Yes, Insurgency content is required, however in the future I plan to upload the content so people who do not own Insurgency can still use the pack.
