### ISSUE TITLE
Guns are errors and/or just black

### ISSUE THREAD

**Issue by Sco00bySnacks** [Gmod4phun/phunbase_ins2#5]
Im prob really stupid but even with all the content installed, ins2 guns (default and custom) are either black or just missing textures with no firing sound and only the gmod hands working. The KF2 weapons work, and the MW2019 ones work (other than they shoot red "x's"). I made a video showing it (quality bad cuz i didn't want to upload for 6000 hours): https://www.youtube.com/watch?v=quSxrdP-YCI

**Comment by Gmod4phun** [comment]
Looks like missing assets, can't really help with that other than make sure you don't have a fuckton of addons, since there is a limit of things that can be loaded, and also make sure you have Insurgency content mounted (not TFA INS2).

**Comment by Sco00bySnacks** [comment]
i just had to mount the ins source mod. ty for help
